### ISSUE TITLE
Buggy cue playback on PHAzOR

### ISSUE THREAD

**Issue by minecrafter37224521** [Taiko2k/TauonMusicBox#475] opened 2021-02-26 22:57 UTC
On two single-file FLAC+cue albums, I am having similar but different problems with PHAzOR. When I try to play the second to last track (track 25) on one album, it will instead play the last track of that album(track 26), but only if it is the first song I play in that instance of Tauon (it doesn't happen if I've previously played any song). On the same album, when track 25 ends, track 26 is skipped and Tauon goes straight to the next album (this happens even if I have previously played something). When any song from the other album is the first song played in that instance of Tauon, the first song from that album is what plays.

**Comment by Taiko2k** [comment] 2021-03-06 06:42
Weird. Can you confirm this behavior on the current version of Tauon? (v6.5.3). Also, to clarify, are you getting expected behavior with GStreamer? (Just not PHAzOR?)

**Comment by minecrafter37224521** [comment] 2021-03-08 19:03
> Weird. Can you confirm this behavior on the current version of Tauon? (v6.5.3). Also, to clarify, are you getting expected behavior with GStreamer selected? (Just not PHAzOR?)

I confirmed that it is still doing this, and it has been with only PHAzOR. I've been using GStreamer since getting this issue and have had no problems.

**Comment by Taiko2k** [comment] 2021-03-20 02:45
Ive identified and fixed an issue where Phazor was incorrectly calculating positions in some cases. I assume this is likely the cause of the issue you repored and is hopefully fixed in v6.5.4

**Closed** 2021-07-06 07:45 UTC
Labels: bug
