### ISSUE TITLE
Manually jumping to a different track sometimes causes a gap before crossfading

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#698] opened 2022-03-02 00:29 UTC
Sometimes when I click to a new track in the playlist, there is a brief pause during which the audio stops completely before it resumes and crossfades to the new track.

My music collection is on a spinning HDD, so there can be a brief access delay with files that aren't yet cached by the OS. I'm guessing this situation can cause tauon to miss an audio buffer as it doesn't want to start the crossfade until the new file is available? Either way it is a bit disruptive.

**Comment by Taiko2k** [comment] 2022-03-19 00:52
> it doesn't want to start the crossfade until the new file is available

Yep it seems that this was the issue. I've committed a change for this now so it will start the crossfade immediately rather than waiting for the file to load. I haven't done a ton of testing but I think with this the issue is fixed.

**Comment by Taiko2k** [comment] 2022-05-18 02:04
I'm hoping this is fixed in the latest v7.2.0, let me know if you still see the issue

**Closed by Taiko2k** 2022-05-18 02:04 UTC
Labels: bug
