### ISSUE TITLE
sometimes tauon starts from a random point in a song

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#879] opened 2022-11-21 02:00 UTC
well i guess the title explains everything, sometimes it happens i press play on a song and tauon just starts from a random point in the song, i have to start the song again to let it start from the beginning

**Comment by Taiko2k** [comment] 2022-11-21 07:51
Can you tell if there is any pattern as to when this happens?

**Comment by legacychimera247** [comment] 2022-11-21 12:06
double click to start on the playlist, and no, the seek bar is exactly at the start

unfortunately i can't tell you if it's random or not

**Comment by Taiko2k** [comment] 2022-11-22 00:24
Do you use CUE sheets in your library much?

**Comment by legacychimera247** [comment] 2022-11-22 10:49
a little yes

**Comment by dondretrotman** [comment] 2022-12-08 01:18
I have the same issue. I am connecting to a Jellyfin server over my network. I am using the Windows binary. I have a playlist going and occasionally (maybe every 1 in 7 tracks?) the next song will start at some random point but not at the beginning. I've made the following observations:

1. The time at the bottom right will count from 00:00 even though the song starts from the middle. 
2. The seek bar starts at the beginning even though the song does not start from the beginning. After the song ends the rest of the track is silent.
3. If I click on the seek bar, the song plays from the correct corresponding location. If I stop and start the track it starts from the beginning as expected.
4. I'm not sure if this is the same issue, but sometimes the track is entirely silent. It is as though the song started at the end in that case. It happens rarely so I didn't test if clicking the seek bar fixes it, but stopping and starting the track starts it from the beginning.

To recreate:
1. Connect Tauon to Jellyfin
2. Generate a playlist (in my case it's a shuffled track)
3. Select the first track and press play. For me, the issue happens randomly so I don't know if it can be reliably replicated.

I don't use CUE sheets in my library

I'll include my conf file with the jellyfin information redacted.
[tauon.txt](https://github.com/Taiko2k/TauonMusicBox/files/10181172/tauon.txt)

**Comment by Taiko2k** [comment] 2022-12-08 07:33
@dondretrotman At least if its happening that often it should be easier to test. Ill get you to run a version of Tauon in which ive added some more debugging info.

 1. Update your install using this installer https://github.com/Taiko2k/TauonMusicBox/releases/download/v7.4.5/TauonMusicBox.v7.4.6-testing1.x64.exe
 2. Open tauon and try replicate the issue.
 3. Right after the issue happens, press the tilde key <kbd>~</kbd>, then press copy. Paste that here (you can redact any personal info if present).

Also, does it ever happen after double clicking a track to play, the transition once the end of a song is reached, or both? 

Also, can you tell me if it ever happens with local files rather than jellyfin?

**Comment by dondretrotman** [comment] 2022-12-09 02:18
It happens sometimes after doubleclicking a track. That's actually how it happened in the output below. I let it play for a few songs and then doubleclicked the next track. So yes it happens in both circumstances. I have not tried it with local files. I don't know if this is relevant, but my playlist has 932 songs.

The issue happened in the Fernando -> The Way We Were / Try to Remember transition. 

`21:32:44 Phazor did not respond with a duration
21:32:44 Transition gapless
21:32:45 Precache next track
21:32:46 DEBUG: Position set by show playing
21:37:44 open - requested start was 0 (0)
21:37:44 mp3
21:37:44 got cached file
21:37:44 四季ノ唄 -> You're So Vain
21:37:44  --- length: 300.094
21:37:44  --- position: 298.108
21:37:44  --- We are 1.98599999999999 from end
21:37:44 Phazor did not respond with a duration
21:37:44 Transition gapless
21:37:45 Precache next track
21:37:46 DEBUG: Position set by show playing
21:42:03 open - requested start was 0 (0)
21:42:03 mp3
21:42:03 got cached file
21:42:03 You're So Vain -> Live to Tell
21:42:03  --- length: 258.951
21:42:03  --- position: 256.959
21:42:03  --- We are 1.9920000000000186 from end
21:42:03 Phazor did not respond with a duration
21:42:03 Transition gapless
21:42:04 Precache next track
21:42:05 DEBUG: Position set by show playing
21:42:06 Auto save playtime
21:47:53 open - requested start was 0 (0)
21:47:53 mp3
21:47:53 got cached file
21:47:53 Live to Tell -> Fernando
21:47:53  --- length: 349.91
21:47:53  --- position: 347.905
21:47:53  --- We are 2.0050000000000523 from end
21:47:53 Phazor did not respond with a duration
21:47:53 Transition gapless
21:47:54 Precache next track
21:47:54 DEBUG: Position set by show playing
21:49:04 open - requested start was 0 (0)
21:49:04 mp3
21:49:04 got cached file
21:49:04 Fernando -> The Way We Were / Try to Remember
21:49:04  --- length: 251.872
21:49:04  --- position: 69.457
21:49:04  --- We are 182.41500000000002 from end
21:49:04 Phazor did not respond with a duration
21:49:04 Transition jump
21:49:05 Precache next track
21:49:16 Message: Lines copied to clipboard
21:52:06 Auto save playtime`

**Comment by Taiko2k** [comment] 2022-12-09 02:42
Hmm, one thing to rule out would be if its related to MP3's specifically. Do you have any FLAC's in your library? (or any other codec) If so, try isolate them to their own playlist and see if you can replicate with any non MP3 files.

To isolate for example FLAC files:

 1. Go to your main playlist.
 2. Press <kbd>Ctrl</kbd> + <kbd>f</kbd>.
 3. Type `.flac`
 4. Press <kbd>Shift</kbd> + <kbd>Enter</kbd>.

**Comment by dondretrotman** [comment] 2022-12-09 12:08
No, I strictly only have MP3s in my library. I'll have to convert some and test but it might take a while.

**Comment by dondretrotman** [comment] 2022-12-12 17:54
Ok so I followed your instructions, and got a playlist of .flac files going. I loaded the playlist, skipped forward to the next track a few times and it happened at 13:48:01 Blown Wide Open -> Break My Stride so it still happens just as randomly. 

13:47:45  --- position: 5.184
13:47:45  --- We are 269.83299999999997 from end
13:47:45 Phazor did not respond with a duration
13:47:45 Transition jump
13:47:48 DEBUG: Position set by show playing
13:47:48 open - requested start was 0 (0)
13:47:48 flac
13:47:48 ABORT
13:47:48 Download file
13:47:49 I Started a Joke -> A Lifetime
13:47:49  --- length: 190.04
13:47:49  --- position: 2.735
13:47:49  --- We are 187.30499999999998 from end
13:47:49 Phazor did not respond with a duration
13:47:49 Transition jump
13:47:52 DEBUG: Position set by show playing
13:47:52 open - requested start was 0 (0)
13:47:52 flac
13:47:52 ABORT
13:47:52 Download file
13:47:53 A Lifetime -> At the Stars
13:47:53  --- length: 216.111
13:47:53  --- position: 3.211
13:47:53  --- We are 212.89999999999998 from end
13:47:53 Phazor did not respond with a duration
13:47:53 Transition jump
13:47:55 open - requested start was 0 (0)
13:47:55 flac
13:47:55 DEBUG: Position set by show playing
13:47:55 ABORT
13:47:55 Download file
13:47:55 At the Stars -> Blown Wide Open
13:47:55  --- length: 223.399
13:47:55  --- position: 2.089
13:47:55  --- We are 221.31 from end
13:47:55 Phazor did not respond with a duration
13:47:55 Transition jump
13:48:00 DEBUG: Position set by show playing
13:48:00 open - requested start was 0 (0)
13:48:00 flac
13:48:00 ABORT
13:48:00 Download file
13:48:01 Blown Wide Open -> Break My Stride
13:48:01  --- length: 355.186
13:48:01  --- position: 4.742
13:48:01  --- We are 350.44399999999996 from end
13:48:01 Phazor did not respond with a duration
13:48:01 Transition jump
13:48:08 DONE
13:48:29 Message: Lines copied to clipboard

**Comment by Korothi** [comment] 2022-12-13 14:05
Same issue here.
Arch Linux
Sometimes it doesn't want to play at all.

**Comment by Taiko2k** [comment] 2022-12-14 00:33
Eureka. I see now! The issue is related to the setting "Avoid Resampling" under Setting -> Audio. For now, you can just disable that setting as a workaround until I figure out a fix for this.

**Comment by legacychimera247** [comment] 2022-12-14 13:30
i hate to be the black sheep but in my case it was already disabled...

**Comment by Korothi** [comment] 2022-12-14 14:10
> Eureka. I see now! The issue is related to the setting "Avoid Resampling" under Setting -> Audio. For now, you can just disable that setting as a workaround until I figure out a fix for this.

i had it enabled. will see how it works when disabled.

**Comment by dondretrotman** [comment] 2022-12-17 00:37
I disabled the "Avoid Resampling" option and I have not encountered the issue. Thanks for your work. I'll look forward to the bugfix.

**Closed** 2023-05-17 08:14 UTC
Labels: bug
