### ISSUE TITLE
Window does not update and pulls the image from the browser

### ISSUE THREAD

**Issue by yuannan** [Taiko2k/TauonMusicBox#294] opened 2020-06-18 13:59 UTC
See image below. When I switch desktops in i3-gaps sometimes the window will not update and then show a image from my browser. Not sure it's just Firefox but it seems to be any hardware accelerated application.

I'm using Arch Linux 5.7.2-zen1-1-zen with a GTX 1080 on NVIDIA 440.82 with kde plasma with i3-gaps as the WM.

Great work on the player, it's been my go to on Linux :) Thank you your great work even in these times 👍 

![image](https://user-images.githubusercontent.com/8006928/85029089-d28c8000-b173-11ea-9163-39ca10dc0dcc.png)

**Comment by Taiko2k** [comment] 2020-06-18 15:59
Unfortunately this will indeed be video driver related. So not much I can likely do about it.

I wonder, does a re-draw revert it to normal? (Like when a song is playing and the seek bar updates)

**Comment by yuannan** [comment] 2020-06-18 16:13
> Unfortunately this will indeed be video driver related. So not much I can likely do about it.
> 
> I wonder, does a re-draw revert it to normal? (Like when a song is playing and the seek bar updates)

Yes, even just mousing over it makes it redraw and it's all fine. Do you know where I can look for support?

**Comment by Taiko2k** [comment] 2020-06-18 16:16
Its possible I'm not property redrawing in response to an event when I should. I'll look into it and we can see if that might fix it.

**Comment by Taiko2k** [comment] 2020-06-19 01:38
Since its doing it to many things, that's indicative of a wider issue. I'd suggest perusing your distros support channels (That's usually where you go, then they open bugs upstream if necessary is the idea).

**Comment by Taiko2k** [comment] 2020-07-01 03:09
I'll close this. If the issue is still persisting, I don't think there's anything I can do to fix it.

**Closed by Taiko2k** 2020-07-01 03:09 UTC
