### ISSUE TITLE
Various suggestions

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#123] opened 2019-05-26 17:53 UTC
- album artist
- composer (also missing in track info)
- comment

-------

There's some weird behavior in regards to the date tag. All my music is tagged via the following date format: year-month-day (yyyy-mm-dd). Lots of albums only display year (yyyy) in Tauon, several display year-day-month (yyyy-dd-mm), while some correctly display year-month-day (yyyy-mm-dd).

**Comment by Taiko2k** [comment] 2019-05-27 02:25
- ***album artist:*** Sure, I can add this.
 - ***composer:*** I can look at adding this to the *columns* view, though I'm not sure where it should go in the track info box, its pretty crammed as it is.
- ***comment**:* Hmm... I never thought of that as being useful to see in column view.

As for the date tags... in most places (like the track info box), Tauon displays it exactly as it is formatted in the tag. Maybe theirs a correlation of behavior between different file types? We might need to look more closely at a specific file to see whats going on exactly.

**Comment by StrangeSeasOfThought** [comment] 2019-05-27 06:17
![playlist](https://user-images.githubusercontent.com/43582772/58398729-41bda080-8056-11e9-8325-9d422cac6cd4.png)
![be1](https://user-images.githubusercontent.com/43582772/58398733-45512780-8056-11e9-98ee-91f45b4c9772.png)
![be2](https://user-images.githubusercontent.com/43582772/58398741-484c1800-8056-11e9-945c-ef9401eca125.png)

I noticed that dates with UTF16 text encoding are being displayed correctly, while dates with a ISO-8859-1 text encoding aren't.

**Comment by Taiko2k** [comment] 2019-05-27 06:20
What file format/codec are these?

**Comment by StrangeSeasOfThought** [comment] 2019-05-27 06:23
All are mp3.

**Comment by Taiko2k** [comment] 2019-05-27 06:56
Yeah I'm not sure whats going on there exactly... I actually use a 3rd party library for reading ID3 tags, so I don't think it's something I can easily fix. I guess the answer is to re-tag all your music in UTF16? 

**\*Taiko2 runs away\***

**Comment by StrangeSeasOfThought** [comment] 2019-05-27 11:39
> I guess the answer is to re-tag all your music in UTF16?

Yeah, or UTF8. Already done. Everything's fine now.

**Comment by StrangeSeasOfThought** [comment] 2019-05-27 11:48
> * _**composer:**_ I can look at adding this to the _columns_ view, though I'm not sure where it should go in the track info box, its pretty crammed as it is.

How about right below Album Artist, same row as Duration?

> * _**comment**:_ Hmm... I never thought of that as being useful to see in column view.
I use the tag mainly for translations of track titles. So it'd be quite useful to be able to display them alongside or instead of titles.

**Comment by Taiko2k** [comment] 2019-05-27 12:24
Okay, I've added these now.

**Comment by StrangeSeasOfThought** [comment] 2019-06-05 06:30
- There seems to be an issue with reading or displaying the _composer_ tag. Reloading metadata didn't help, the column remains empty.

- To save some space in column view, it'd be better for the album artist column to display the artist if album artist tag is empty (basically like the album artist list view does). Or maybe an additional column called _Album Artist or Artist_.

- Another tag for column view: _Grouping_ (I use this one to describe the album type: studio album, extended play, single album, ...).

- Themes: It'd be great to be able to color more/all tags in the column view by editing the theme files.

**Comment by Taiko2k** [comment] 2019-06-05 07:32
- **Album-Artist column**: I was thinking this too. It won't save space per se, but will make the list look cleaner and draw attention only if there is meaningful information there.  I have committed this change now.

  As for adding another column... doesn't seem like an ideal solution... I guess.

> Note: You will need to re-add the Album-Artist column for it to work again.

- ***Grouping***... this tag field is really rare in my experience. I think it might be better to avoid the menu list getting too cumbersome. And unfortunately, due to the current way the tag-scanning and database are coded, its not simple to have user defined columns unfortunately. (perhaps that is something to look into though)

- **Column colours**: OK, I have added this now. How it works is like this, in the theme file, for example:
 ```
240,50,50		column-codec
50,240,50		column-comment
50,50,240		column-title
240,50,240		column-album-artist
```
where the format is `column-`*`name`* where *name* is the title of the column as it appears in the app. I haven't made any changes to the existing themes, but you can add these entires. Without adding anything, the colours will remain as they were previously.

**Comment by StrangeSeasOfThought** [comment] 2019-06-05 16:04
> * **Album-Artist column**: I was thinking this too. It won't save space per se, but will make the list look cleaner and draw attention only if there is meaningful information there.  I have committed this change now.

I didn't notice any difference. However, I managed to achieve what I wanted by changing it to: #124 

> where the format is `column-`_`name`_ where _name_ is the title of the column as it appears in the app. I haven't made any changes to the existing themes, but you can add these entires. Without adding anything, the colours will remain as they were previously.

That's awesome! Cheers!

**Comment by Taiko2k** [comment] 2019-06-06 03:38
- **Pull req** Oh, I see what you mean now. Actually, I think this behavior is "wrong", since there would now be cases where that column will be displaying artists that are not the album artist. I might add a setting for this that defaults to off (The other option would be making another column as you mentioned, but... I think that might be getting too cluttered)

- **Column colours** I've now added syntax for specifying colour of the playing line. (Its different in some themes). It looks like this:
  ```
   200,50,200		column-album-artist
   200,200,50		column+album-artist
   ```
  Where column+ is the row of the playing track. 

- **Folder line** Hmm... I think there can be cases where the folder name would give more information than just album title alone, sometimes the album-artist may be in the folder title but not in the tag.... but as you say, there are other cases where the title in the folder name is not properly formatted. Might be easier to just keep the current behavior.

- **Hide bar** I did this on purpose because there would be no way to get it back otherwise. I suppose I should make this persistent and make a setting in the settings somewhere for it. 

- **Searchable tags** OK, I have now added album-artist (merged with 'artist') and composer (its own highlight) to the search overlay. I skipped comment, because I think that might slow the search down too much if there happen to be comments with a lot of text.

- **1** I think this behavior is preferred, but perhaps a setting for this would be useful.

- **2** I think what might be happening is the right-side-panel is not longer fully extended when switching to maximized, and the existing behavior is to hide that bottom text if the metadata is shown in the side panel.

  I think that is preferred behavior when the window is small, but perhaps it should be always shown if the size of the window is large.

**Comment by StrangeSeasOfThought** [comment] 2019-06-06 12:59
> * **2** I think what might be happening is the right-side-panel is no longer fully extended when switching to maximized, and the existing behavior is to hide that bottom text if the metadata is shown in the side panel.

Ah, right. Basically to prevent duplication of the same information (artist & title) in the bottom area.
However, as far as I can tell, it's being displayed there in every other viewing mode, so I naturally tend to look there first and feel like it should always be there, even if it's only for consistency. v0v

**Comment by StrangeSeasOfThought** [comment] 2019-06-07 19:07
- When I use _Sorted... Loved_ all my loved songs are correctly listed, however, the artist list view only shows 3 of the 40-ish artists.
It seems like only artists with at least 5 loved songs are being displayed in the artist list view. Is this intended?

**Comment by Taiko2k** [comment] 2019-06-07 21:00
Yes, its intended to reduce *noise* so to speak. Perhaps this needs to be more dynamic / show all artists if the playlist is relatively short so that this is less noticeable.

**Comment by StrangeSeasOfThought** [comment] 2019-06-08 09:32
> Yes, its intended to reduce _noise_ so to speak. Perhaps this needs to be more dynamic / show all artists if the playlist is relatively short so that this is less noticeable.

I'd like that. And thank you for the latest commits, the app looks even more stunning now!

> * I think that is preferred behavior when the window is small, but perhaps it should be always shown if the size of the window is large. (edit: committed)

It's still missing when the app is maximized...?

**Comment by Taiko2k** [comment] 2019-06-08 11:13
- OK, ive fixed those two things.
- **Mock up:** Maybe. I'm not sure this should be the default as the album-artist field isn't super common... Ive pushed a config option for this following your mock up `left-aligned-album-artist-title`:

![Screenshot from 2019-06-08 23-10-51](https://user-images.githubusercontent.com/17271572/59146473-be7f5000-8a42-11e9-9b5c-a26a60bec83e.png)

**Comment by StrangeSeasOfThought** [comment] 2019-06-08 15:04
Thanks!

- Artists with a small first letter are now being sorted to the end of the playlist.

**Comment by Taiko2k** [comment] 2019-06-09 08:45
- Fixed these two case sensitivity issues now
- As for the auto stop, I've changed the behavior to match what you described. I do think this is more intuitive and offers more control.

**Comment by StrangeSeasOfThought** [comment] 2019-06-09 09:38
I'm running low on suggestions to give now...

How about for the showcase vis to use the album artwork's main colors? The artwork often represents the mood of an album.
For example, right now, I'm listening to a darker album, but the visualization is using a bright green color.
Well, it's not too important, maybe more of a long-term goal that can also be combined with #68.

**Comment by Taiko2k** [comment] 2019-06-09 09:57
> I'm running low on suggestions to give now...

That's okay. Thanks for giving them. I appreciate the help.

> How about for the showcase vis to use the album artwork's main colors?

An interesting idea, ill keep it in mind. (Though, I'm guessing that darker colours won't show as good on the dark background)

**Comment by StrangeSeasOfThought** [comment] 2019-06-09 11:10
- Mini Mode Micro: The following happens quite often when I want to move it around:

![micro](https://user-images.githubusercontent.com/43582772/59158267-ca592980-8ab7-11e9-9b96-18feced82516.png)

(KDE Plasma)

**Comment by Taiko2k** [comment] 2019-06-09 12:42
OK, I've added a setting to stop those **notifications**.

As for the mini mode issue, I gave it a quick test, but was not able to replicate the issue. Are there any other correlations? Like does it do it if something is playing or not? Are the window button unresponsive (even if you click where they should be)?

Strange you say it does it when moving the window... sounds like a rendering issue. Maybe you could try change the ***Rending Backend*** setting to OpenGL 3.1. No idea if that will do anything or not.

![scr44](https://user-images.githubusercontent.com/17271572/59158998-328b2800-8b17-11e9-8c94-08219e3cc725.png)

**Add to queue**
I *could* add this... similar to how if you right click a folder title, it gives the alternate option `Add album to queue - after current album`. But I'm hesitant to since I don't want the track menu to get too big (maybe show on <kbd>Shift</kbd> hold). 

Yeah, adding before the album sounds better, I really don't wanna change the album grouping behavior (it would be a bit of a headache to change, and I don't think swapping to listing every track would be great UX)

**Comment by StrangeSeasOfThought** [comment] 2019-06-09 12:47
> Yeah, adding before the album sounds better

yep, I forgot about it being _Up Next_, so that'd be fine (as long as the album doesn't restart from track #1).

**Comment by Taiko2k** [comment] 2019-06-09 12:49
With the current implementation, that would indeed cause an interruption and would restart from first track again (it doesn't keep track of how far you are though the album)

**Comment by StrangeSeasOfThought** [comment] 2019-06-09 12:51
> Like does it do it if something is playing or not? Are the window button unresponsive (even if you click where they should be)?

When music is playing, playback also continues, window buttons are unresponsive. Right click pause/unpause does work.

**Comment by Taiko2k** [comment] 2019-06-09 13:03
> Should've been OpenGL 3.1 to begin with

Its not the default (idk why, maybe there's a reason)

**Comment by StrangeSeasOfThought** [comment] 2019-06-09 13:06
- Enhancement, Mini Mode: A way to swap to a different mode (like Shift+click).

**Comment by Taiko2k** [comment] 2019-06-09 13:12
> A way to swap to a different mode (like Shift+click).

I suppose it would cycle them all... but I don't think that's particularly useful

> Mouse-over progress bar in micro mode

This sounds like a good idea to me. Like a thin progress bar at the bottom. I could try cram in a forward button also.

**Comment by StrangeSeasOfThought** [comment] 2019-06-09 13:17
> I could try cram in a forward button also.
Most keyboards should have media keys, so I don't think that'd be necessary. Most DE should also have tool tips like this:

![micro2](https://user-images.githubusercontent.com/43582772/59159423-bcac9f80-8ac9-11e9-96e8-18eef6837e0e.png)

**Comment by Taiko2k** [comment] 2019-06-09 13:21
I think you might have a point there, and just having the seek bar would look more minimal / nicer.

> Maybe the repeat and shuffle buttons instead?

I can't think of a way to add these in that looks nice but not too small that its a UX problem.

**Comment by StrangeSeasOfThought** [comment] 2019-06-09 13:26
> I suppose it would cycle them all... but I don't think that's particularly useful

Well, sometimes I want to take a closer look at the artwork but I'm ~stuck in micro mode, exiting mini mode just to look at the artwork seems like overkill. Maybe only cycle micro and square?

**Comment by Taiko2k** [comment] 2019-06-09 13:28
> Maybe only cycle micro and square?

Yeah, that sounds better.

**Comment by StrangeSeasOfThought** [comment] 2019-06-09 20:15
- Queue: When adding an album to queue, followed by a track, the track won't be played immediately after the album. Instead, the very next track in playlist will be played first. After this track, the queued one will be played.

**Comment by Taiko2k** [comment] 2019-06-10 01:52
> the track won't be played immediately after the album

I can't seem to replicate this issue. Can you find any conditions in particular that cause it to happen, or do you find that it always happens?

**Comment by StrangeSeasOfThought** [comment] 2019-06-10 07:02
> but the issue will resume on restart.

Indeed...

> I can't seem to replicate this issue. Can you find any conditions in particular that cause it to happen, or do you find that it always happens?

I'm investigating now.

**Comment by Taiko2k** [comment] 2019-06-10 07:24
Oh, I see. The issue is related specifically to single track albums.

**Comment by StrangeSeasOfThought** [comment] 2019-06-10 07:27
- Enhancement, Queue: Double click track/album on queue to immediately play track/album. If it is a track, it'll also be removed from queue. If it is an album, it'll be moved to the top of the queue.

**Comment by Taiko2k** [comment] 2019-06-10 08:05
> The issue is related specifically to single track albums.

OK, I have fixed this (*I think*)

> Double click track/album on queue to immediately play track/album

OK, I have added a menu option named `Play Now`, I think this should work as expected, I only gave it a quick test so far.

> Rather than artist text color, why not use the same color as the main app's seek bar?

Well, its just the artist colour here tends to happen to look nice I think (is also the window button accent) ... and the seek bar colour is just grey in most themes, so that's kinda boring.

> Increase width of Micro slightly 

Okay, I have increased this slightly.

**Comment by StrangeSeasOfThought** [comment] 2019-06-10 08:09
> or split it (current behavior)?

This.

**Comment by Taiko2k** [comment] 2019-06-10 08:33
> Crop Others. Similiar to Clear Queue

Okay, I've added this and named it `(Clear Queue) ↳ Except for This`. I'm not sure if `Crop Others` would be as immediately obvious as to what it does.

**Comment by StrangeSeasOfThought** [comment] 2019-06-10 14:31
`line 19779
    mini_mode2 = MiniMode2()
             ^
SyntaxError: invalid syntax`

**Comment by StrangeSeasOfThought** [comment] 2019-06-11 09:09
- After playback is stopped: When using the play button again, check if there are queued tracks first. If there are: play the first one.
Right now, the queue is being ignored and the last played track will be played again.

**Comment by Taiko2k** [comment] 2019-06-11 09:32
Actually, I think it should be the behavior with auto-stop to stop and be ready on the next track regardless of the queue. I've made this change. I made an exception for shuffle though, since I think it might be jarring for the position on the playlist to suddenly change.

**Comment by StrangeSeasOfThought** [comment] 2019-06-11 09:49
> I made an exception for shuffle though, since I think it might be jarring for the position of the playlist to suddenly change.

I just noticed that I can use the next track button (to start a random track when shuffle is enabled) instead.

**Comment by StrangeSeasOfThought** [comment] 2019-06-11 10:06
Something else I noticed: Track change notification is the only place where the album title is highlighted instead of the track title:

**Album**
Artist - Title

--------------

**Title**
Artist

**Artist - Title** (maybe too long)
Album

**Title**
Artist | Album

**Title**
_Artist_
Album

**Comment by Taiko2k** [comment] 2019-06-11 10:22
Hmm, yes perhaps that is a bit strange. I think we should go with:

**Artist - Title**
Album

Probably. Makes the most sense to me. Just for curiosity I had a look at how some other players do it:

GNOME MPRIS:
**Artist**
Title

Lollypop:
**Title**
by Artist, from Album

Clementine:
**Artist - Title**
Album

Spotify:
**Title**
Artist - Album

**Comment by StrangeSeasOfThought** [comment] 2019-06-11 10:33
The problem with the first one is: long artist names + long titles...

That's why I'd prefer album titles to be shortened (because that's the least important of the three imo). So...Spotify version, but maybe with | instead of -

**Comment by Taiko2k** [comment] 2019-06-11 10:48
Sound good. I have made this change now. I also made it withdraw the notification after some time now.

**Comment by StrangeSeasOfThought** [comment] 2019-06-11 16:46
- Enhancement, Queue: Total duration of queued tracks:


Playlist I
Playlist II
Playlist III
________________
Up Next:
Track A
Track B
Album 1
Track C
Album 2
Track D
Track E
Album 3
________________
60 Tracks (4:06:57)

**Comment by StrangeSeasOfThought** [comment] 2019-06-11 17:02
- Enhancement, Queue: Total duration of queued tracks:

![queue](https://user-images.githubusercontent.com/43582772/59291483-45b70880-8c7b-11e9-97cb-ad693a8c30ef.png)

**Comment by StrangeSeasOfThought** [comment] 2019-06-11 20:51
> * **Searchable tags** OK, I have now added album-artist (merged with 'artist') and composer (its own highlight) to the search overlay.

Searching for album artist doesn't work.

**Comment by Taiko2k** [comment] 2019-06-11 23:15
> Searching for album artist doesn't work.

I found and fixed a bug with this now

> Hotkey for Global search please.

OK, I've added this now. (I'm guessing the current way was awkward to use with an IME.)

You will need to manually add the entry `global-search G Ctrl` to the `input.txt` in your user data folder.

**Comment by StrangeSeasOfThought** [comment] 2019-06-12 06:39
- Enhancement, Queue: If there's no queue yet, it's not possible to drag and drop a track, a new playlist will be created instead. So, always show the line seperating playlist from queue, drag and drop above for playlist, below for queue?

- I also encountered a crash when trying to drag and drop multiple selected tracks (clicking folder line) to queue.

**Comment by Taiko2k** [comment] 2019-06-12 07:01
> I wasn't able to replicate this again, so I'll keep my eye on it for now.

This can happen if you reposition the album in the playlist. I've made some changes mitigate this now.

> So, always show the line seperating playlist from queue

Okay, Ive made this change, lets see how it goes.

> I also encountered a crash when trying to drag and drop multiple selected tracks (clicking folder line) to queue.

Fixed.

**Comment by StrangeSeasOfThought** [comment] 2019-06-12 07:11
> > I wasn't able to replicate this again, so I'll keep my eye on it for now.
> 
> This can happen if you reposition the album in the playlist. I've made some changes mitigate this now.

It just happened again, by adding album to queue via right click in gallery, so no repositioning. (I haven't updated, yet, though.)

**Comment by Taiko2k** [comment] 2019-06-12 08:35
> I haven't updated, yet, though.

I think the fix might have covered whatever was causing that too.

> Enhancement, add Tooltips

Yeah, Columns mode should probably have this so I'll give that priority. I've hacked this in now.

**Comment by StrangeSeasOfThought** [comment] 2019-06-12 13:13
By the way:

![tauon32](https://user-images.githubusercontent.com/43582772/59353766-009ae100-8d24-11e9-9146-296642714ba5.png)

Tauon Music Box + Manjaro32 (i686) Xfce

Slightly sluggish, but otherwise runs quite  well on 13 year old notebook I sometimes use as a music server.

**Comment by StrangeSeasOfThought** [comment] 2019-06-13 16:30
- App crashes when trying to enter any Mini mode.

**Comment by Taiko2k** [comment] 2019-06-14 02:42
Okay, I have added these.

**Comment by StrangeSeasOfThought** [comment] 2019-06-14 19:06
- Not sure if this already happens automatically, but if not: Manually refresh artist info text/biography via right click menu.

**Comment by Taiko2k** [comment] 2019-06-15 02:15
> Not sure if this already happens automatically, but if not: Manually refresh artist info text/biography via right click menu.

You can currently remove them all by deleting the cache folder, but yeah there should be an easier way of flushing specific artists bio's.

**Comment by Taiko2k** [comment] 2019-06-16 07:06
> Manually refresh artist info text/biography via right click menu.

I've now added a "Reload Bio" option to the menu (Hold shift to reveal) (Only reloads text, not the image)

**Comment by StrangeSeasOfThought** [comment] 2019-06-20 21:02
> * Queue: When adding an album to queue, followed by a track, the track won't be played immediately after the album. Instead, the very next track in playlist will be played first. After this track, the queued one will be played.



> > The issue is related specifically to single track albums.
> 
> OK, I have fixed this (_I think_)


Happened again today, however, after a multitrack album this time.

**Comment by Taiko2k** [comment] 2019-06-20 22:39
> Happened again today, but after a grouped multitrack album this time.

OK, I've made some changes, hopefully fixed for reals this time. 

(I found I was able to replicate this if I manually jump to the last track in the album, it would play the next track in the playlist after, since the check that the album has ended only happened on the 2nd to last track of the album. I've now made it check on the last track too.)

**Closed** 2019-06-21 06:43 UTC
Labels: enhancement
