### ISSUE TITLE
[Feature Request] Minimize to tray option on linux

### ISSUE THREAD

**Issue by Zzombiee2361** [Taiko2k/TauonMusicBox#417] opened 2020-11-10 02:23 UTC
Please reconsider to add this on linux

**Comment by Taiko2k** [comment] 2020-11-10 08:35
Okay, I've committed this feature now.

Here's how it looks:

![Screenshot from 2020-11-10 21-26-27](https://user-images.githubusercontent.com/17271572/98648873-b811a800-239b-11eb-9418-f1673753e1c7.png)

Here's showing the small playing symbol when the app is playing and also the menu:

![Screenshot from 2020-11-10 21-26-57-cropped](https://user-images.githubusercontent.com/17271572/98648989-decfde80-239b-11eb-91e1-541899ce9f13.jpg)

Here's the new settings that you will need to enable:

![Screenshot from 2020-11-10 21-32-37](https://user-images.githubusercontent.com/17271572/98649260-4554fc80-239c-11eb-9f0d-8ea1b0f7e39e.png)

This should work in KDE, but on GNOME this will require an extension such as "Appindicator and kstatusnotiferitem`.

**Comment by Solarunit** [comment] 2020-11-10 10:31
@Taiko2k is it possible to show "artist - song" info as well?

**Comment by Solarunit** [comment] 2020-11-10 10:38
>Here's showing the small playing symbol when the app is playing and also the menu:

what about a pause symbol? 
I am not sure about Repeat and Shuffle, because there would be two symbols: playing + repeat

**Comment by Taiko2k** [comment] 2020-11-10 12:48
> what about a pause symbol?

Okay I've added this now.

![Screenshot from 2020-11-11 00-37-26](https://user-images.githubusercontent.com/17271572/98669297-177cb180-23b6-11eb-984a-43088c252067.png)

> I am not sure about Repeat and Shuffle, because there might be two (or even three) symbols

Yeah I also think that would start to look messy.

> is it possible to show "artist - song" info as well (on the right side of the icon)?

Mmmmmmm okay!

![Screenshot from 2020-11-11 00-21-45](https://user-images.githubusercontent.com/17271572/98669414-39763400-23b6-11eb-93f4-801ab996c302.png)

Hey that looks pretty cool! Doesn't seem to work on KDE though, not sure it supports it.

**Comment by Zzombiee2361** [comment] 2020-11-10 13:36
Whoa whoa, text on a tray icon? That seems so weird. There is already extensions or plasmoids that does the same thing for all mpris2 player. It's better to put these info on the tooltip (it exists on KDE, not sure about GNOME)

**Comment by Solarunit** [comment] 2020-11-11 00:43
>Mmmmmmm okay!

Nnnnnnice!
But it is optional, right?

I have some ideas:

1. Click on the song name reveals the mini-playlist [probably overkill]
2. Mouse hover over the song name reveals the control buttons (previous | play/pause | next ) while the text is hidden [probably overkill]
3. Repeat and Shuffle indicators, but I don't know where to put them [nice to have]
4. Customizable text (background?) color for the artist and song name, transparency setting [probably overkill]

>Hey that looks pretty cool! Doesn't seem to work on KDE though, not sure it supports it.

I wonder how it will look on Solus Budgie

**Comment by Taiko2k** [comment] 2020-11-11 00:54
> But it is optional, right?

Yep. Settings looks like this now:

![Screenshot from 2020-11-11 13-48-36](https://user-images.githubusercontent.com/17271572/98751303-c0fa8c00-2424-11eb-9bb1-61b082f68c6d.png)

> I have some ideas

That text is already pushing the limit of what Appindicators can do. In fact clicking can only bring up the one menu. For more one would need to write a full shell extension, but as mentioned, those can be done by a dedicated MPRIS extension.

**Comment by Solarunit** [comment] 2020-11-11 01:06
> That text is already pushing the limit of what Appindicators can do. In fact clicking can only bring up the one menu. For more one would need to write a full shell extension, but as mentioned, those can be done by a dedicated MPRIS extension.

Okay =)
I am patiently waiting for the next Flatpak release.

**Comment by Solarunit** [comment] 2020-11-17 08:25
@Taiko2k I can see the tray icon in the Solus Budgie tray!

![](https://i.imgur.com/0JZgRQQ.png)

 but there are some problems:

- play/pause indicator sometimes doesn't work + there is a small delay
- when track is playing, left or right click on the tray icon crashes Tauon, so no menu...
- **show title text** doesn't work :cry:

**Comment by Taiko2k** [comment] 2020-11-17 09:54
> but there are some problems:

Yep, I just tested in Budgie and can replicate the menu crash. Must be a bug in some package. Not much I can do about it.

It does seem to switch playing/pause icon alright for me though. No text either, it must not be implemented on budgie's tray.

**Comment by Solarunit** [comment] 2020-11-17 10:03
> It does seem to switch playing/pause icon alright for me though. 

Sometimes it freezes for me.

>No text either, it must not be implemented on budgie's tray.

Ok, I've asked at the Solus forum about the issue.

**Comment by Solarunit** [comment] 2020-11-17 10:17
> It does seem to switch playing/pause icon alright for me though.

Did you try to chaotically click play and pause buttons to reproduce the issue?

![](https://i.imgur.com/06LCme4.png)

BTW i am using Play|pause global hotkey

**Comment by Taiko2k** [comment] 2020-11-17 10:34
@Solarunit Oh yeah you're right, its freezes often. I think its budgie related since it works when testing in GNOME for me. Again, not much I can do.

**Comment by Solarunit** [comment] 2020-11-17 10:38
@Taiko2k I hope something we could do on the Budgie side. Thanks =)

**Comment by Solarunit** [comment] 2020-11-17 11:07
@Taiko2k I switched to the Phazor and testing now:

- no delay
- no freezes so far

**Comment by Solarunit** [comment] 2020-11-17 22:59
@Taiko2k Well, Solus Budgie supports the xembed-based system trays at the moment...

**Comment by Zzombiee2361** [comment] 2020-11-20 04:12
Ok, just tested this. But the minimize to tray doesn't really work, tried minimizing but it's still on task bar, then tried closing but it just closes the app. Honestly it should be close to tray instead of minimize to tray, because other music player do this. I also can reproduce @Solarunit issue where sometimes the pause icon stuck.

Also, it would be quite useful if TMB's tooltip could show some song info like clementine or strawberry music player does:
![image](https://user-images.githubusercontent.com/37852137/99756966-f5570200-2b20-11eb-9da2-c4bde9b0db0a.png)

**Comment by Taiko2k** [comment] 2020-11-20 04:15
> But the minimize to tray doesn't really work, tried minimizing but it's still on task bar

Is the setting "Minimize to tray" enabled?

**Comment by Zzombiee2361** [comment] 2020-11-20 05:26
Yes, it is enabled
![Peek 2020-11-20 12-25](https://user-images.githubusercontent.com/37852137/99762655-93e86080-2b2b-11eb-9f9e-5a016b85a065.gif)

**Comment by Taiko2k** [comment] 2020-11-20 05:35
I see, that's a bug in that its not working when using the system minimize button rather than Tauon's own one.

**Comment by Zzombiee2361** [comment] 2020-11-20 05:42
Can confirm. Also found another bug, if I minimize it to tray before playing anything (no play or pause icon yet) the tray menu won't open. That said, can you please change the minimize to tray behavior to close to tray? Every other player that has tray icon use this behavior.

**Comment by Taiko2k** [comment] 2020-11-20 10:39
> the tray menu won't open

I cant seem to replicate this. Also doesn't make sense to me that changing the icon would make it then work.

> minimize to tray behavior to close to tray

Okay, I've committed this change in behavior now. The setting now reads "Close to tray"

> useful if TMB's tooltip could show some song info

Okay committed this too, so the tooltip will now show the song title like that.

>  I also can reproduce @Solarunit issue where sometimes the pause icon stuck.

Ive identified and fixed an issue where it wouldn't return to playing if controlling via mipris. I wonder if that was the same issue you experienced.

**Comment by Zzombiee2361** [comment] 2020-11-20 17:17
> I cant seem to replicate this. Also doesn't make sense to me that changing the icon would make it then work.

My bad, I can't reproduce this again. Thanks for the behavior and the tooltip.

> Ive identified and fixed an issue where it wouldn't return to playing if controlling via mipris. I wonder if that was the same issue you experienced.

Here's how I could reproduce it, can you reproduce it too after fixing that issue?
![Peek 2020-11-21 00-12](https://user-images.githubusercontent.com/37852137/99829073-6aacec00-2b8e-11eb-96b5-49f181c50ebd.gif)

**Comment by Taiko2k** [comment] 2020-11-21 07:55
> Here's how I could reproduce it, can you reproduce it too after fixing that issue?

Oh right that also causes it, fixed that too now.

**Closed** 2020-12-03 10:45 UTC
Labels: enhancement

**Comment by Solarunit** [comment] 2020-12-03 11:15
Tauon 6.4.4. Unfortunately the feature doesn't work correctly in Budgie. I have to disable it :cry:

**Comment by Taiko2k** [comment] 2020-12-03 11:29
>  Unfortunately the feature doesn't work correctly in Budgie.

Wontfix sorry. This current solution is the best of the worst. I'm not interested in using a different implementation at this point :weary:
