### ISSUE TITLE
Same cover multiple times for no reason?

### ISSUE THREAD

**Issue by Darkmaster006** [Taiko2k/TauonMusicBox#514] opened 2021-04-29 06:00 UTC
Basically, I see the same cover twice, thrice, or more times, when the tags are the same.
![imagen](https://user-images.githubusercontent.com/21136515/116508085-f9890780-a896-11eb-9b8d-9b1ecbce0a67.png)

**Comment by Taiko2k** [comment] 2021-04-29 06:12
This looks like a kind of transient error that happens sometimes. Try close then open the gallery and see if that flushes the error.

**Comment by Darkmaster006** [comment] 2021-04-29 07:26
> This looks like a kind of transient error that happens sometimes. Try close then open the gallery and see if that flushes the error.

Indeed, it is a transient error. Why does it happen, though? Weird. I did not do anything at all, just had Tauon open, and it fixed itself out of the blue.
![imagen](https://user-images.githubusercontent.com/21136515/116515700-04499980-a8a3-11eb-9a07-7acdc43a5611.png)

**Comment by Darkmaster006** [comment] 2021-04-29 08:19
This seems to happen when I click the 'Artist' (or any other) tab. Right now:
![imagen](https://user-images.githubusercontent.com/21136515/116521370-432f1d80-a8aa-11eb-9073-816b92415bbf.png)
After clicking 'Artist':
![imagen](https://user-images.githubusercontent.com/21136515/116521400-4a562b80-a8aa-11eb-9b7d-3a14d205a819.png)
After clicking 'Genre':
![imagen](https://user-images.githubusercontent.com/21136515/116521493-6ce84480-a8aa-11eb-994a-bb7ffd39ce0a.png)

**Comment by Taiko2k** [comment] 2021-04-29 08:22
This happens when the gallery data falls out of sync with the playlist data. Normally, when a playlist is modified, it notifies the gallery to update, the issue is some actions don't do this.

If you can list the actions that trigger the issue, it shouldn't be too hard to fix. Seems like clicking the column titles is one of them?

**Comment by Darkmaster006** [comment] 2021-04-29 08:24
> This happens when the gallery data falls out of sync with the playlist data. Normally, when a playlist is modified, it notifies the gallery to update, the issue is some actions don't do this.
> 
> If you can list the actions that trigger the issue, it shouldn't be too hard to fix. Seems like clicking the column titles is one of them?

Yeah, exactly, it seems like clicking the column titles trigger it, so far that's the only one I found.

**Comment by Taiko2k** [comment] 2021-05-07 09:48
I've now committed a fix for that

**Closed** 2021-05-10 02:13 UTC
Labels: bug
