### ISSUE TITLE
Option for just sync, as well as transcode and sync.

### ISSUE THREAD

**Issue by mannp** [Taiko2k/TauonMusicBox#300] opened 2020-07-05 15:57 UTC
Love the new sync option, thanks :)

For my phones its great but for a hires audio player, I'd prefer not to transcode, so wondered if it was a possibility to just do transfer and sync rather than transcode and sync?

Thanks for the consideration.

**Comment by Taiko2k** [comment] 2020-07-05 22:15
Okay, I've committed a change.

There will now be a setting to toggle the transcode part.

![Screenshot from 2020-07-06 10-10-31](https://user-images.githubusercontent.com/17271572/86543321-8e6ded80-bf71-11ea-9c92-ebcbc73e4f69.png)

**Comment by mannp** [comment] 2020-07-05 22:44
Wow, that's great and thanks for the very quick response and change 😃 

btw, how do I unset a playlist for sync? I can right click the playlist and set sync, but I cannot unset it? Thanks... I can create another issue if you prefer...

**Comment by Taiko2k** [comment] 2020-07-05 23:00
> btw, how do I unset a playlist for sync?

You can't currently. But yes it might make things clearer if I add that.

(Actually, technically you can currently by creating a new playlist, setting is as the sync playlist, then deleting it)

**Comment by mannp** [comment] 2020-07-06 08:52
> > btw, how do I unset a playlist for sync?
> 
> You can't currently (It doesn't do anything automatically so it doesn't matter really). But yes it might make things clearer if I add that.
> 
> (Actually, technically you can currently by creating a new playlist, setting is as the sync playlist, then deleting it)

Thanks for the clarification.

I wondered as I initially set my flac playlist as sync, then created a specific playlist for my hires device and selected sync... I didn't realise but all my flacs were transcoded to the device :)

Not sure if that is by design or an additional feature ...

**Closed** 2020-07-06 09:04 UTC
Labels: enhancement

**Comment by Taiko2k** [comment] 2020-07-06 10:07
> I wondered as I initially set my flac playlist as sync, then created a specific playlist for my hires device and selected sync... I didn't realise but all my flacs were transcoded to the device :)

If you set your flac playlist as the sync source, that makes sense right?

**Comment by mannp** [comment] 2020-07-06 11:30
> > I wondered as I initially set my flac playlist as sync, then created a specific playlist for my hires device and selected sync... I didn't realise but all my flacs were transcoded to the device :)
> 
> If you set your flac playlist as the sync source, that makes sense right?

Yes, if multiple sync sources are selectable.

Now we have an unsync source we can see if we had selected as a sync source, so should be manageable now.

**Comment by Taiko2k** [comment] 2020-07-06 11:36
There can only be one sync source playlist at a time. Selecting another unselects the last. (At least, that's the intended behaviour)

**Comment by mannp** [comment] 2020-07-06 11:39
> There can only be one sync source playlist at a time. Selecting another unselects the last. (At least, that's the intended behaviour)

Okay so, I selected, flac playlist as sync, then hires as sync, so it should have deselected the flac playlist.

It didn't for me, but you've since updated the app, so will leave this closed and open another if I can reproduce.
