### ISSUE TITLE
Tauon v7.4.4 keeps crashing

### ISSUE THREAD

**Issue by Scotty-Trees** [Taiko2k/TauonMusicBox#881] opened 2022-11-25 16:07 UTC
Just updated Tauon this morning and I was able to play a few songs, then it just stopped working, so I closed it and opened it up again and now every time I try to play a song it just keeps crashing. When running the Tauon flatpak from the terminal and I attempt to play a song it crashes, so here is the output for that which I hope may be helpful:

```
scott@ubuntu:~$ flatpak run com.github.taiko2k.tauonmb
Tauon Music Box v7.4.4
Copyright 2015-2022 Taiko2k captain.gxj@gmail.com

Window size: [1600, 926]
Gtk-Message: 10:57:03.623: Failed to load module "canberra-gtk-module"
Detected running as Flatpak
Installed as Flatpak
User files location: /home/scott/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/scott/Downloads
Found XDG-Music: /home/scott/Music
Install directory: /app/bin
Database loaded in 0.149 seconds.
Copy tray icons to data directory...
Error loading xcursor
Scanning for chromecasts...
Start controller server
Start PHAzOR backend...
Using SDL version: 2.0.16
Applying theme: Carbon
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 326, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 44617, in <module>
    playlist_render.full_render()
  File "/app/bin/t_modules/t_main.py", line 33386, in full_render
    pctl.jump(track_id, track_position)
  File "/app/bin/t_modules/t_main.py", line 5442, in jump
    self.play_target(jump=jump)
  File "/app/bin/t_modules/t_main.py", line 5397, in play_target
    self.update_change()
  File "/app/bin/t_modules/t_main.py", line 5417, in update_change
    album_art_gen.display(target, (0, 0), (50, 50), theme_only=True)
  File "/app/bin/t_modules/t_main.py", line 12142, in display
    filepath = track.fullpath
AttributeError: 'str' object has no attribute 'fullpath'
ph: Connected using samplerate 44100hz
scott@ubuntu:~$ 
```

And here's my system info:

```
scott@ubuntu:~$ inxi -Fzx
System:
  Kernel: 5.15.0-53-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: GNOME 42.5 Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Machine:
  Type: Laptop System: Acer product: Aspire E5-576G v: V1.32
    serial: <superuser required>
  Mobo: KBL model: Ironman_SK v: V1.32 serial: <superuser required>
    UEFI: Insyde v: 1.32 date: 10/24/2017
Battery:
  ID-1: BAT1 charge: 9.6 Wh (100.0%) condition: 9.6/62.2 Wh (15.5%)
    volts: 12.7 min: 11.1 model: PANASONIC AS16B5J status: Full
CPU:
  Info: quad core model: Intel Core i5-8250U bits: 64 type: MT MCP
    arch: Coffee Lake rev: A cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 3400 high: 3401 min/max: 400/3400 cores: 1: 3400
    2: 3400 3: 3400 4: 3401 5: 3401 6: 3399 7: 3400 8: 3400 bogomips: 28800
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel UHD Graphics 620 vendor: Acer Incorporated ALI driver: i915
    v: kernel bus-ID: 00:02.0
  Device-2: NVIDIA GP108M [GeForce MX150] vendor: Acer Incorporated ALI
    driver: nvidia v: 515.65.01 bus-ID: 01:00.0
  Device-3: Chicony HD WebCam type: USB driver: uvcvideo bus-ID: 1-7:4
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce MX150/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.65.01 direct render: Yes
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: Acer Incorporated ALI
    driver: snd_hda_intel v: kernel bus-ID: 00:1f.3
  Sound Server-1: ALSA v: k5.15.0-53-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
    v: kernel bus-ID: 03:00.0
  IF: wlp3s0 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Acer Incorporated ALI driver: r8169 v: kernel port: 3000
    bus-ID: 04:00.1
  IF: enp4s0f1 state: down mac: <filter>
Bluetooth:
  Device-1: Intel Wireless-AC 3168 Bluetooth type: USB driver: btusb v: 0.8
    bus-ID: 1-5:3
  Report: hciconfig ID: hci0 rfk-id: 2 state: up address: <filter>
    bt-v: 2.1 lmp-v: 4.2
Drives:
  Local Storage: total: 238.47 GiB used: 148.64 GiB (62.3%)
  ID-1: /dev/sda vendor: SK Hynix model: HFS256G39TND-N210A
    size: 238.47 GiB
Partition:
  ID-1: / size: 229.63 GiB used: 148.39 GiB (64.6%) fs: ext4 dev: /dev/dm-1
    mapped: vgubuntu-root
  ID-2: /boot size: 1.61 GiB used: 251.5 MiB (15.3%) fs: ext4
    dev: /dev/sda2
  ID-3: /boot/efi size: 511 MiB used: 5.2 MiB (1.0%) fs: vfat
    dev: /dev/sda1
Swap:
  ID-1: swap-1 type: partition size: 1.91 GiB used: 0 KiB (0.0%)
    dev: /dev/dm-2 mapped: vgubuntu-swap_1
Sensors:
  System Temperatures: cpu: 64.0 C pch: 58.5 C mobo: N/A gpu: nvidia
    temp: 56 C
  Fan Speeds (RPM): N/A
Info:
  Processes: 306 Uptime: 33m Memory: 15.5 GiB used: 3.71 GiB (23.9%)
  Init: systemd runlevel: 5 Compilers: gcc: N/A Packages: 2229 Shell: Bash
  v: 5.1.16 inxi: 3.3.13
```

**Comment by Scotty-Trees** [comment] 2022-11-25 17:20
[simplescreenrecorder-2022-11-25_12.10.51.webm](https://user-images.githubusercontent.com/45135187/204031292-c5427974-5518-4607-82d2-b1f0036570b5.webm)

Also, in this video which demonstrates the crash when I click on some (not all) of my songs, which didn't crash before the v7.4.4 update, I would also like to demonstrate that in v7.4.4 when clicking an album artwork, the song no longer becomes highlighted or selected in the tracklist. When I used to click on an album, it would highlight the track to the left in the list. Now when I click an album, no track is highlight, so you never know what track your even on. Clicking the album artwork again reveals a highlight, but this is not useful behavior, a single album artwork click should highlight the deserved track. 

Hopefully this can be resolved with a quick hotfix! As always, thanks very much for making the best linux music player!

**Comment by Scotty-Trees** [comment] 2022-11-25 18:00
Here's another one, I was able to play only 2 tracks before it crashed, essentially Tauon isn't usable in it's current state, but I hope I can help offer any additional logs if you need of course, more than happy to help if I can!

```
scott@ubuntu:~$ flatpak run com.github.taiko2k.tauonmb
Tauon Music Box v7.4.4
Copyright 2015-2022 Taiko2k captain.gxj@gmail.com

Window size: [1600, 926]
Gtk-Message: 12:48:03.515: Failed to load module "canberra-gtk-module"
Detected running as Flatpak
Installed as Flatpak
User files location: /home/scott/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/scott/Downloads
Found XDG-Music: /home/scott/Music
Install directory: /app/bin
Database loaded in 0.145 seconds.
Copy tray icons to data directory...
Error loading xcursor
Scanning for chromecasts...
Start controller server
Start PHAzOR backend...
Using SDL version: 2.0.16
Applying theme: Carbon
Gallery render error!
ph: Connected using samplerate 44100hz
Attempting to connect to Last.fm network
Connection to lastfm appears successful
ph: Connected using samplerate 44100hz
ph: Connected using samplerate 44100hz
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_phazor.py", line 811, in player4
    pctl.advance(quiet=True, end=True)
  File "/app/bin/t_modules/t_main.py", line 6437, in advance
    self.play_target(jump=not end)
  File "/app/bin/t_modules/t_main.py", line 5397, in play_target
    self.update_change()
  File "/app/bin/t_modules/t_main.py", line 5417, in update_change
    album_art_gen.display(target, (0, 0), (50, 50), theme_only=True)
  File "/app/bin/t_modules/t_main.py", line 12142, in display
    filepath = track.fullpath
AttributeError: 'str' object has no attribute 'fullpath'
Submit Scrobble The Last Ten Seconds of Life - Dreams of Extermination
submitting scrobble...
Start PHAzOR backend...
ph: Cannot init. Main loop already running!
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 326, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 44617, in <module>
    playlist_render.full_render()
  File "/app/bin/t_modules/t_main.py", line 33386, in full_render
    pctl.jump(track_id, track_position)
  File "/app/bin/t_modules/t_main.py", line 5442, in jump
    self.play_target(jump=jump)
  File "/app/bin/t_modules/t_main.py", line 5397, in play_target
    self.update_change()
  File "/app/bin/t_modules/t_main.py", line 5417, in update_change
    album_art_gen.display(target, (0, 0), (50, 50), theme_only=True)
  File "/app/bin/t_modules/t_main.py", line 12142, in display
    filepath = track.fullpath
AttributeError: 'str' object has no attribute 'fullpath'
```

**Comment by Taiko2k** [comment] 2022-11-25 20:09
Looks like its a bug with "auto theme", disabling that should resolve the crashing for now, ill try get an update with a bugfix out soon

**Comment by Scotty-Trees** [comment] 2022-11-25 20:24
Can confirm, switching to other themes results in normal behavior consistent with how Tauon has meant to function in the past. I've always enjoyed using and loving the **Carbon** theme for its ability to use colors based on the current album art, but I will take your advice and stick to another theme for the time being. 

Currently using the Turbo theme now and no more crashes to report (phew that's a relief!). Also, thanks for getting back to me so quickly, you never disappoint!

**Comment by Taiko2k** [comment] 2022-11-25 20:41
No worries. I should have a Flatpak update out within the hour. Let me know if the issue is fixed with it.

**Comment by Scotty-Trees** [comment] 2022-11-25 21:05
Just update to v7.4.5 of the flatpak. Did a few tests, looks all good now. I can no longer reproduce the error and the theme Carbon once again functions correctly. Thanks again for the speedy replies and speedy updates. Feel free to mark this issue as solved at your earliest convenience.

**Closed** 2022-11-27 08:30 UTC
