### ISSUE TITLE
Crash when minimize to tray

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#184] opened 2019-10-11 23:13 UTC
```
  File "/opt/tauon-music-box/tauon.py", line 5556, in draw_window_tools
    if tray.active and prefs.min_to_tray:
NameError: name 'tray' is not defined
```

**Comment by Taiko2k** [comment] 2019-10-11 23:27
Oh, caused by some shuffling of code I did. Pushed a fix.

**Closed by Taiko2k** 2019-10-11 23:27 UTC
