### ISSUE TITLE
Incorrect filename sort

### ISSUE THREAD

**Issue by david-cortes** [Taiko2k/TauonMusicBox#746] opened 2022-05-11 20:17 UTC
I have a saved playlist with two albums inside it and each album has filenames starting with numbers (all files live in the same folder), and have the UI configured to show the file name as one of the columns/fields in playlists.

If I click the "Filename" column to sort entries in the playlist by it, it produces an incorrect order:
![filename_bad_sort](https://user-images.githubusercontent.com/11860098/167939955-f937258d-4dd8-4fde-9929-65149b12e1cb.png)

**Comment by Taiko2k** [comment] 2022-05-13 10:20
After investigating this myself, I see that this sorting column is indeed very broken. Actually fixing it to work as was intended (to sort the playlist by the file**name** *as-is* probably isn't desirable in any case, so I've changed the behaviour to sort by file*path* regardless. I've committed this fix now so it will be ready for next release.

**Closed** 2022-05-14 08:29 UTC
Labels: bug
