### ISSUE TITLE
Mpris does not work properly with Tauon.

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#187] opened 2019-10-15 16:08 UTC
After following your suggestion and using mpris to show music info on polybar, I have experienced some nagging behaviour. When I load Tauon, and start playing, polybar only shows the stop button instead of the playing track. I have to reload bspwm or restart polybar for it to work properly. I tested other music players, like Cantata and Cmus and they all behaved as expected; polybar immidiately updated and showed me the info I needed.  

I also noticed that this behavour is only when the `player-mpris-tail.py` file is used because the ` player-mpris-simple.sh` works fine. I don't want to use `player-mpris-simple.sh` because it is slow to update and can take up to 3 seconds to register any change. If it is any help,  here is my polybar mpris module:

``` [module/player-mpris-tail]
type = custom/script
exec = ~/.config/polybar/scripts/player-mpris-tail.py -f '{icon} {:artist:t20:{artist}:}{:artist: - :}{:t20:{title}:}'
tail = true
format-foreground = ${colors.foreground}
format-background = ${colors.background}
label = %output%
```
I don't know if this is a problem with the mpris python script or Tauon.

**Comment by Taiko2k** [comment] 2019-10-16 02:41
I have been able to replicate the issue, but I'm not sure what the cause is. I've opened an issue about it on polybar-scripts https://github.com/polybar/polybar-scripts/issues/188

**Comment by keystroke3** [comment] 2019-10-16 08:02
I am glad you were able to replicate it, I thought my system had a problem. I hope you are able to get an answer on the polybar repo and post an update on this issue.

**Comment by keystroke3** [comment] 2019-10-18 17:55
Hi, @Cybolic added a fix to the tail script. https://github.com/polybar/polybar-scripts/pull/189. But it still does not work. Could you maybe look at it?

**Comment by Taiko2k** [comment] 2019-10-18 19:11
@keystroke3 The change does appear to solve the issue for me. Are you sure you updated your script?

**Comment by keystroke3** [comment] 2019-10-18 19:39
Oh, it works now. I forgot polybar only reloads when you edit its own config. When I reloaded bspwm, the changes were applied. It now works properly.

**Comment by Cybolic** [comment] 2019-10-18 19:39
I've added an extra way for the player to be discovered. I had to purposefully break other things to actually get this code path to fire in testing, so it really shouldn't actually ever run, but it _really, really_ should pick up the player now.

**Comment by Cybolic** [comment] 2019-10-18 19:39
Oh, good to hear! :)

**Comment by keystroke3** [comment] 2019-10-18 19:41
Thanks for your quick action. I appreciate the script because it saves me a lot of time.

**Comment by x70b1** [comment] 2019-10-18 20:09
PR is merged at `polybar-scripts`.

**Closed** 2019-10-18 20:31 UTC
